### PR TITLE
Add firula expression

### LINKED ISSUE #352: Add expression: firula
From Algolia

### PR DESCRIPTION
**Pull request by angelod1as**
Closes #352

---
**important**: I could not install the app on my computer (something to do with Ruby and M1 macs), so I did not test the implementation.

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Thank you!! I haven't had time, but at some point I will probably switch to Hugo or another static site generator as I also have issues with Ruby sometimes.

**Comment by angelod1as** [comment]
@kinow I dunno what's your stack, but I'm pretty used to Nextjs and Vercel as deployment platform.

**Comment by kinow** [comment]
> @kinow I dunno what's your stack, but I'm pretty used to Nextjs and Vercel as deployment platform.

Never used Vercel, but looks similar to Netlify. I don't have a strong preference, but previously the site was hosted on a Linode VM. Then it got downsized after I moved overseas/left my company.

Then I moved everything to GitHub, since I was using it for the code versioning. So code + deployment on GitHub, and removed the MySQL+PHP part by this Jekyll+custom plugins+Algolia.

It works well, and the maintenance cost is really small. Just Ruby keep breaking every now and then, so will probably ditch it for another part, but the deployment with GH Actions + GH Pages so far works great.

Will look at Nextjs too when I have time to work on the move from Ruby to something else, thanks!

**Comment by angelod1as** [comment]
@kinow if you want any support on that, send me a message or email. I can't apply as a maintainer but I can help occasionally for sure.

**Comment by kinow** [comment]
Thank you @angelod1as ! And if you have any more interesting expressions, feel free to submit them here :+1: 

Looks like yours was deployed successfully, and the Algolia index must have been updated too, so available in the search: https://speaklikeabrazilian.com/f/firula/

**Pull request merged**
